version: '3'

services:
  apache:

    image: httpd:2.4
    restart: always
    volumes:
      - ${APP_PATH}:${WORK_DIR}
      - ./services/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - app
    environment:
      - APACHE_RUN_USER=www-data
      - PHP_PORT=${PHP_PROXY}
      - PHP_PROXY=${PHP_PROXY}
      - WORK_DIR=${PUBLIC_DIR}
      - PUBLIC_DIR=${PUBLIC_DIR}

  nginx:
    image: nginx:1.21.6
    environment:
      WORK_DIR: ${PUBLIC_DIR}
    restart: always
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_PATH}:${WORK_DIR}
      - ./services/nginx/nginx.conf:/etc/nginx/nginx_example.conf
    depends_on:
      - apache
    command: ["/bin/bash", "-c", "export WORK_DIR && envsubst '$$WORK_DIR' < /etc/nginx/nginx_example.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
        
  # horizon:
  #   build:
  #     ./services/horizon
  #   restart: always
  #   volumes:
  #     - ${APP_PATH}:${WORK_DIR}
  #   environment:
  #     - WORK_DIR=${WORK_DIR}
  #   depends_on:
  #     - app

  # webskockets:
  #   build:
  #     ./services/webskockets
  #   restart: always
  #   volumes:
  #     - ${APP_PATH}:${WORK_DIR}
  #   environment:
  #     - WORK_DIR=${WORK_DIR}
  #   ports:
  #     - '${LARAVEL_WEBSOCKETS_PORT:-6001}:6001'
  #   depends_on:
  #     - app

  app:
    restart: always
    build:
      ./services/app
    volumes:
      - ${APP_PATH}:${WORK_DIR}
      - ./services/app/php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - mariadb
      - redis
    environment:
      - WORK_DIR=${WORK_DIR}
    # command: /bin/bash -c "php artisan storage:link && php artisan migrate && php artisan config:cache && php-fpm"


  mariadb:
    image: mariadb:10.7
    restart: always
    volumes:
      - ${DATABASE_PATH}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
      - mariadb:db
    ports:
      - ${PMA_PORT}:80
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
      - mariadb
  # redis:
  #   image: bitnami/redis:6.2.7
  #   restart: always
  #   volumes:
  #     - ${REDIS_PATH}:/bitnami/redis/data
  #   ports: 
  #    - ${REDIS_PORT}:6379
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   user: root
